"""empty message

Revision ID: 1a127b66d8fa
Revises: 7fd3fdeb38b3
Create Date: 2025-05-15 15:42:51.678081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a127b66d8fa'
down_revision = '7fd3fdeb38b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('total_cgt',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_column('total_sell')
        batch_op.drop_column('total_buy')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('total_buy', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('total_sell', sa.FLOAT(), nullable=True))
        batch_op.alter_column('filename',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.alter_column('total_cgt',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
