"""empty message

Revision ID: 4f0060be9faf
Revises: a0b79aba6adb
Create Date: 2025-05-14 23:07:26.268333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f0060be9faf'
down_revision = 'a0b79aba6adb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_cgt', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('filename', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.drop_column('filename')
        batch_op.drop_column('total_cgt')

    # ### end Alembic commands ###
