"""empty message

Revision ID: 77fcc390944f
Revises: da337c9a8a0b
Create Date: 2025-05-14 23:30:55.026695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77fcc390944f'
down_revision = 'da337c9a8a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_summary')
    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.TEXT(length=150),
               type_=sa.String(length=150),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.TEXT(length=150),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(length=150),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(length=150),
               type_=sa.String(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(length=150),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(length=150),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(length=150),
               existing_nullable=False)

    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(length=150),
               existing_nullable=True)

    op.create_table('_alembic_tmp_summary',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('total_buy', sa.FLOAT(), nullable=True),
    sa.Column('total_sell', sa.FLOAT(), nullable=True),
    sa.Column('total_cgt', sa.FLOAT(), nullable=True),
    sa.Column('filename', sa.VARCHAR(length=150), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
