"""empty message

Revision ID: 9f0722cc665d
Revises: 77fcc390944f
Create Date: 2025-05-15 13:04:26.904390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f0722cc665d'
down_revision = '77fcc390944f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
