"""empty message

Revision ID: a2109556c27c
Revises: e09b7219f9fb
Create Date: 2025-05-15 23:47:26.546572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2109556c27c'
down_revision = 'e09b7219f9fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pnl_graph', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.drop_column('pnl_graph')

    # ### end Alembic commands ###
