"""empty message

Revision ID: b9cbf3932f5b
Revises: 4f0060be9faf
Create Date: 2025-05-14 23:28:35.875752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9cbf3932f5b'
down_revision = '4f0060be9faf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.TEXT(length=150),
               type_=sa.String(length=150),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.TEXT(length=150),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(length=150),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(length=150),
               type_=sa.String(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(length=150),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(length=150),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(length=150),
               existing_nullable=False)

    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(length=150),
               existing_nullable=True)

    # ### end Alembic commands ###
