"""empty message

Revision ID: da337c9a8a0b
Revises: b9cbf3932f5b
Create Date: 2025-05-14 23:29:39.824059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da337c9a8a0b'
down_revision = 'b9cbf3932f5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.TEXT(length=150),
               type_=sa.String(length=150),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.TEXT(length=150),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(length=150),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(length=150),
               type_=sa.String(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(length=150),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(length=150),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(length=150),
               existing_nullable=False)

    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(length=150),
               nullable=True)

    # ### end Alembic commands ###
