"""empty message

Revision ID: e09b7219f9fb
Revises: 1a127b66d8fa
Create Date: 2025-05-15 18:03:56.462621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e09b7219f9fb'
down_revision = '1a127b66d8fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_cost', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('total_mv', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.drop_column('total_mv')
        batch_op.drop_column('total_cost')

    # ### end Alembic commands ###
